config/routes.rb
Rails.application.routes.draw do
  get 'welcome/index'

  root 'welcome#index'

get 'about', to: 'pages#about'
get 'location', to: 'pages#location'
get 'public/forms.pdf' => 'welcome#download'

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController

    def about
    
    end
    
    def location
        
    end
    
  
    
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  
    
  end

  def download
    send_file 'public/forms.pdf'
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/layouts/_navigation.erb
<div class="navbar navbar-inverse">
  <div class="container">
    <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-responsive-collapse">
      <span class="icon-bar"></span>
      <span class="icon-bar"></span>
      <span class="icon-bar"></span>
    </button>
    <%= link_to 'Dr. Gregory Gould', root_path, class: "navbar-brand", id:"logo" %>
    <div class="navbar-collapse collapse navbar-responsive-collapse">
      <ul class="nav navbar-nav">
        <li><%= link_to "Home", root_path  %></li>
        <li><%= link_to "About Us", about_path  %></li>
        <li><%= link_to "Location", location_path  %></li>
        
      </ul>
    </div>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=Edge,chrome=1">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title><%= content_for?(:title) ? yield(:title) : "DrGould" %></title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag "application", :media => "all" %>

    <!-- For third-generation iPad with high-resolution Retina display: -->
    <!-- Size should be 144 x 144 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-144x144-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '144x144' %>

    <!-- For iPhone with high-resolution Retina display: -->
    <!-- Size should be 114 x 114 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-114x114-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '114x114' %>

    <!-- For first- and second-generation iPad: -->
    <!-- Size should be 72 x 72 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-72x72-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '72x72' %>

    <!-- For non-Retina iPhone, iPod Touch, and Android 2.1+ devices: -->
    <!-- Size should be 57 x 57 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png' %>

    <!-- For all other devices -->
    <!-- Size should be 32 x 32 pixels -->
    <%= favicon_link_tag 'favicon.ico', :rel => 'shortcut icon' %>

    <%= javascript_include_tag "application" %>

    <!-- Le HTML5 shim, for IE6-8 support of HTML elements -->
    <!--[if lt IE 9]>
    <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/3.7.2/html5shiv.min.js" type="text/javascript"></script>
    <![endif]-->
  </head>
  <body>

    <%= render 'layouts/navigation' %>

    <div class="container">
      <div class="row">
          <%= bootstrap_flash %>
          <%= yield %>
      </div><!--/row-->

      <footer>
        <p>&copy; Dr. Gregory E. Gould 2016</p>
      </footer>
    </div>
  </body>
</html>

app/views/pages/about.html.erb
<h1>About Us</h1>
<div class="container center">
    <div class="center row">
        <div class="col-md-7">
            <p>"Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor 
            incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud 
            exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure 
            dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. 
            Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit 
            anim id est laborum."</p>
             <p>"Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor 
            incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud 
            exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure 
            dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. 
            Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit 
            anim id est laborum."</p>
        </div>
        <div class="col-md-4">
            <%= image_tag('Gould.jpeg', width: "500", id:"about-pic", class:"img-rounded") %>
        </div>
    </div>
</div>

app/views/pages/location.html.erb
<h1>Location</h1>
<div class="container">
    <div class="row">
        <div class="col col-md-4">
            <h2>Address:</h2>
            <div class="well">
                <a href="https://goo.gl/maps/GSfdsreSQCz">Gregory E. Gould, D.O., P.C.</br>
                60005 Campground Road, Suite 600</br>
                Washington, MI  48094</a>
            </div>
            <h2>Phone:</h2>
            <div class="well">
                <a href="tel:586-372-3500">586-372-3500</a>
            </div>
        </div>
        <div class="col col-md-8">
            <h2>Map:</h2>
            <iframe id="map" src="https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d39979.91433706821!2d-83.03584053255886!3d42.733044714127615!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x8824e5d345252529%3A0x163da58c81dd0aff!2sGregory+E.+Gould%2C+DO+PC!5e0!3m2!1sen!2sus!4v1458519352821" 
            width="620" height="400" frameborder="0" style="border:0" allowfullscreen></iframe>
        </div>
        
    </div>
</div>

app/views/welcome/index.html.erb
<div class="container">
    <div class="row">
        <div class= "center jumbotron" id="index_page_img">
            <h1>Dr. Gregory Gould</h1>
            <div class="row">
                <div class="col-lg-7"></div>
                <div class="col-lg-5">
                    <div class="container" id="black-background">
                        <p>We do primary care the way it was always supposed to be done. </p>
                    </div>
                </div>
            </div>
            <div id="right-top-padding">
                <%= link_to "Learn More", about_path, id:"top-padding", class:"btn btn-primary btn-lg "%>
            </div>
        </div>
    </div>
</div>
<div class="container">
<div class="panel panel-default">
  <div class="panel-body" id="index-panel">
    Coming in for an appointment?  Save time and <strong>download the necessary forms <%=link_to "here", 'public/forms.pdf' %>.</strong> 
  </div>
</div>
</div>